### ISSUE TITLE
Kiwix Desktop 2.0.1-1 appimage is not able to play video ZIM file

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#430]
The whole pages are blank.

Tested with Ubuntu 20.04 with https://download.kiwix.org/zim/other/mali-pour-les-nuls_fr_all_2020-04.zim

**Comment by kelson42** [comment]
The bug is still there with 2.0.3.

**Comment by kelson42** [comment]
@probonopd I believe your help would be welcome here, do you have any comment on this kind of problem?

**Comment by probonopd** [comment]
Hi @kelson42 basically one needs to run from the command line, and watch for error messages there.

**Comment by kelson42** [comment]
@probonopd Yes, sorry for the poor ticket quality. Here it is:
```
$ ./kiwix-desktop_x86_64_2.0.4.appimage 
Library directory : "/home/kelson/.local/share/kiwix"
Compiled with Qt Version  5.9.5
Runtime Qt Version  5.9.5
add widget
```

And then at the time I load the ZIM file (welcome page):
```
[269892:269917:0730/121538.425091:ERROR:bad_message.cc(23)] Terminating renderer for bad IPC message, reason 139
```

**Comment by probonopd** [comment]
"Terminating renderer for bad IPC message, reason 139" is not an error that is coming from the AppImage runtime. 

Is a custom URL scheme being used in Kiwix Desktop?

Unfortunately I can't help more here than recommending to Google around for

> "Terminating renderer for bad IPC message, reason 139"

**Comment by kelson42** [comment]
@probonopd Yes, we have a custom scheme and this is a bug we don't have with Flatpak.

**Comment by probonopd** [comment]
It seems to be some sort of crossdomain issue, reason 139 = BDH_DISALLOWED_ORIGIN.

Maybe you don't have the bug with Flatpak because you are using a newer Qt version there? Please bundle the latest Qt (e.g., from https://launchpad.net/~beineri) in the AppImage and then try again.

**Comment by kelson42** [comment]
@mgautierfr Anything you confirm/do here?

**Comment by mgautierfr** [comment]
I think we need to test with a more recent version of Qt yes. Not sure we should spend time on issue that could be already fixed with recent version.

**Comment by probonopd** [comment]
Right, just build with the latest available Qt from https://launchpad.net/~beineri and see if it fixes the issue. Based on some comments in other tickets I think it actually might.

**Comment by mgautierfr** [comment]
Here is a appimage of kiwix-desktop compiled with qt5.14 (from beineri repository) : http://tmp.kiwix.org/Kiwix-test_qt514-x86_64.AppImage

On fedora 32, I had to run it with `MESA_LOADER_DRIVER_OVERRIDE=i965 ./Kiwix-test_qt514-x86_64.AppImage`

**Comment by kelson42** [comment]
@mgautierfr Great. It works perfectly for me:
* No opengl problem at start
* Not problem to play videos

**Comment by kelson42** [comment]
@ubuntu-2020 Would you be able please to test this custon appimage that @mgautierfr has proposed?

**Comment by probonopd** [comment]
Thanks @mgautierfr. Unfortunately it does not launch on my Xubuntu 18.04 system:

```
me@host:~$ Downloads/Kiwix-test_qt514-x86_64.AppImage 
Library directory : "/home/me/.local/share/kiwix"
Compiled with Qt Version  5.14.2
Runtime Qt Version  5.14.2
Trace/breakpoint trap
```

Looking at it with `strace`, I can see

```
uname({sysname="Linux", nodename="host", ...}) = 0
access(":/fonts/Selawik/selawk.ttf", R_OK) = -1 ENOENT (No such file or directory)
access(":/fonts/Selawik/selawkl.ttf", R_OK) = -1 ENOENT (No such file or directory)
access(":/fonts/Selawik/selawksl.ttf", R_OK) = -1 ENOENT (No such file or directory)
access(":/fonts/Selawik/selawksb.ttf", R_OK) = -1 ENOENT (No such file or directory)
access(":/fonts/Selawik/selawkb.ttf", R_OK) = -1 ENOENT (No such file or directory)
access(":/fonts/Selawik/selawk.ttf", R_OK) = -1 ENOENT (No such file or directory)
access(":/fonts/Selawik/selawkl.ttf", R_OK) = -1 ENOENT (No such file or directory)
access(":/fonts/Selawik/selawksl.ttf", R_OK) = -1 ENOENT (No such file or directory)
access(":/fonts/Selawik/selawksb.ttf", R_OK) = -1 ENOENT (No such file or directory)
access(":/fonts/Selawik/selawkb.ttf", R_OK) = -1 ENOENT (No such file or directory)
--- SIGTRAP {si_signo=SIGTRAP, si_code=SI_KERNEL} ---
+++ killed by SIGTRAP +++
Trace/breakpoint trap
```

So manybe it is due to the Selawik fonts being missing?

**Comment by probonopd** [comment]
I wanted to test but https://download.kiwix.org/zim/other/mali-pour-les-nuls_fr_all_2020-04.zim is no longer there. How can I test?

**Comment by kelson42** [comment]
@probonopd Take the latest version https://download.kiwix.org/zim/other/mali-pour-les-nuls_fr_all_2020-07.zim

**Comment by probonopd** [comment]
I can confirm that the video play well in your version @mgautierfr on Xubuntu 18.04. :+1:  (I cannot open it in the "official" AppImage.)

**Comment by kelson42** [comment]
Ok, so bug should be fixed by just upgrading to a recent version of Qt5.

**Comment by probonopd** [comment]
Check these: https://launchpad.net/~beineri

**Comment by PaulSHahn** [comment]
I still have this issue on Lubuntu/Ubuntu Groovy with the official kiwix-desktop_x86_64_2.0.5.appimage I downloaded today.... blank pages with khan academy videos. Exporting the environment variable was no help. May try to build from source later on.

**Comment by kelson42** [comment]
We have now Kiwix Desktop compiling against Qt 5.15 and this fixes the problem. Until the next release, the nightlies from https://download.kiwix.org should allow to fix the problem.
