### ISSUE TITLE
Remember the current directory path in the file explorer over restart

### ISSUE THREAD

**Issue by FractalU** [kiwix/kiwix-desktop#976]
When opening a new zim file via `Open file (ctrl + o)` then the current directory path in the explorer gets reset to the path of the application directory over a restart.

I tested this on kiwix-desktop 2.3.1 on windows 7 and 10.

**Comment by FractalU** [comment]
@kelson42 The best behavior to me would be that the path of the file explorer has been remembered after a restart of kiwix-desktop like I stated in the title. I don't know what would be the best default path of the file explorer. The default path should be practical. Maybe `Downloads` but I don't know. So, it's up to you to decide. Additionally, I tested this behavior on my Pop!_OS 20.04 LTS in a vm (Took me a while to figure out how to run an appimage). For me the current behavior is the same on Pop!_OS as on Windows.

**Comment by kelson42** [comment]
OK, at this stage, not sure what should be the proper behaviour. To some extend, I wonder if this is not the role of the OS to deal with this.

**Comment by FractalU** [comment]
For comparision, I tested Libreoffice on Windows, Pop!_OS and PureOS. Libreoffice remembers the path of open file in the explorer over restart on all those OSes. Kiwix-desktop doesn't remember it over restart. I guess it's not a role of the OS and that it needs a proper implementation.

**Comment by sgourdas** [comment]
I have implemented a solution to this issue. Only thing I was not able to come around doing is making the tags for the multiple languages correlated with `import-dir-dialog-msg` etc. I have setup the placeholders, just not generated the text.

**Comment by sgourdas** [comment]
@mgautierfr let me know if you need any further information to help close this.

I was also thinking of:
- Squashing the commits with a better commit message
- Keeping them separated and changing the commit messages based on logic (memorization - setting)

**Comment by kelson42** [comment]
@sgourdas sorry for the late feedback our side. We will have a look to your PR but for me at that point it still not clear what should be the proper behaviour.
